### Class 7- Starter code


In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model, metrics

###Create sample data and fit a model

In [2]:
df = pd.DataFrame({'x': range(100), 'y': range(100)})
biased_df  = df.copy()
biased_df.loc[:20, 'x'] = 1
biased_df.loc[:20, 'y'] = 1

def append_jitter(series):
    jitter = np.random.random_sample(size=100)
    return series + jitter

df['x'] = append_jitter(df.x)
df['y'] = append_jitter(df.y)

biased_df['x'] = append_jitter(biased_df.x)
biased_df['y'] = append_jitter(biased_df.y)

In [3]:
## fit
lm = linear_model.LinearRegression().fit(df[['x']], df['y'])
print(metrics.mean_squared_error(df['y'], lm.predict(df[['x']])))

0.145997902601


In [4]:
## biased fit
lm = linear_model.LinearRegression().fit(biased_df[['x']], biased_df['y'])
print(metrics.mean_squared_error(df['y'], lm.predict(df[['x']])))

0.147359709433


## Cross validation
#### Intro to cross validation with bike share data from last time. We will be modeling casual ridership. 

In [5]:
from sklearn import cross_validation
wd = '../../../../2_dataset/'
bikeshare = pd.read_csv(wd + 'bikeshare.csv')

####Create dummy variables and set outcome (dependent) variable

In [8]:
weather = pd.get_dummies(bikeshare.weathersit, prefix='weather')
modeldata = bikeshare[['temp', 'hum']].join(weather[['weather_1', 'weather_2', 'weather_3']])
y = bikeshare.casual 

In [9]:
modeldata.head()

temp   hum  weather_1  weather_2  weather_3
0  0.24  0.81          1          0          0
1  0.22  0.80          1          0          0
2  0.22  0.80          1          0          0
3  0.24  0.75          1          0          0
4  0.24  0.75          1          0          0

#### Create a cross valiation with 5 folds

In [ ]:
knn = KNeibors()

In [11]:
modeldata.shape[0]

17379

In [19]:
kf = cross_validation.KFold(len(modeldata), n_folds=11, shuffle=True,random_state=123)

In [20]:
n=0
for train,test in kf:
    print train[:10]
    print test[:10]
    n+=1
    print n

[0 1 2 3 4 5 6 7 8 9]
[ 10  12  24  31  74  81 152 156 159 166]
1
[0 1 2 3 4 5 6 7 8 9]
[ 19  20  34  45  63  66 100 136 139 146]
2
[ 0  1  2  3  4  5  6  7  8 10]
[ 9 15 21 32 48 51 53 67 86 95]
3
[ 0  1  2  3  4  5  6  8  9 10]
[ 7 14 23 28 42 44 46 54 88 97]
4
[ 0  1  4  5  7  9 10 12 13 14]
[  2   3   6   8  11  58  80 121 123 132]
5
[ 1  2  3  5  6  7  8  9 10 11]
[  0   4  30  50  76  84  89  93  99 101]
6
[0 1 2 3 4 5 6 7 8 9]
[27 40 43 55 59 61 68 71 79 82]
7
[0 1 2 3 4 5 6 7 8 9]
[25 33 35 36 39 65 72 77 92 98]
8
[ 0  1  2  3  4  6  7  8  9 10]
[  5  17  18  52  62  64  73  75  94 140]
9
[ 0  2  3  4  5  6  7  8  9 10]
[ 1 13 26 29 38 41 47 49 56 69]
10
[0 1 2 3 4 5 6 7 8 9]
[16 22 37 57 60 70 78 83 87 96]
11


In [21]:
mse_values = []
scores = []
n= 0
print("~~~~ CROSS VALIDATION each fold ~~~~")
for train_index, test_index in kf:
    x_train = modeldata.iloc[train_index]
    x_test = modeldata.iloc[test_index]
    y_train = y.iloc[train_index]
    y_true = y.iloc[test_index]
    
    lm = linear_model.LinearRegression()
    
    lm.fit(x_train,y_train)
    
    y_preds = lm.predict(x_test)
    
    mse_values.append(metrics.mean_squared_error(y_true,y_preds))
    scores.append(lm.score(x_test, y_true))
    n+=1
    print('Model', n)
    print('MSE:', mse_values[n-1])
    print('R2:', scores[n-1])


print("~~~~ SUMMARY OF CROSS VALIDATION ~~~~")
print('Mean of MSE for all folds:', np.mean(mse_values))
print('Mean of R2 for all folds:', np.mean(scores))

~~~~ CROSS VALIDATION each fold ~~~~
('Model', 1)
('MSE:', 1798.9914814013712)
('R2:', 0.27996245972635692)
('Model', 2)
('MSE:', 1631.3548438011326)
('R2:', 0.3065903344793669)
('Model', 3)
('MSE:', 1744.1121440754491)
('R2:', 0.29668304847518701)
('Model', 4)
('MSE:', 1844.4181997474882)
('R2:', 0.30130743221295919)
('Model', 5)
('MSE:', 1621.5274827490166)
('R2:', 0.31688718168018226)
('Model', 6)
('MSE:', 1840.3930783458425)
('R2:', 0.31168275229733078)
('Model', 7)
('MSE:', 1496.4905440295481)
('R2:', 0.32909074848616315)
('Model', 8)
('MSE:', 1479.314441942583)
('R2:', 0.35582903086918305)
('Model', 9)
('MSE:', 1801.1263794622605)
('R2:', 0.30273059913723133)
('Model', 10)
('MSE:', 1522.6681773839584)
('R2:', 0.31526365002016615)
('Model', 11)
('MSE:', 1628.3194566288557)
('R2:', 0.31014164262045474)
~~~~ SUMMARY OF CROSS VALIDATION ~~~~
('Mean of MSE for all folds:', 1673.5196572334098)
('Mean of R2 for all folds:', 0.31146989818223464)


In [18]:
200/1762.0

0.11350737797956867

In [19]:
lm = linear_model.LinearRegression().fit(modeldata, y)
print("~~~~ Single Model ~~~~")
print('MSE of single model:', metrics.mean_squared_error(y, lm.predict(modeldata)))
print('R2: ', lm.score(modeldata, y))

~~~~ Single Model ~~~~
MSE of single model: 1672.58110765
R2:  0.311934605989


### Check
While the cross validated approach here generated more overall error, which of the two approaches would predict new data more accurately: the single model or the cross validated, averaged one? Why?


Answer: 

### There are ways to improve our model with regularization. 
Let's check out the effects on MSE and R2

In [25]:
lm = linear_model.LinearRegression().fit(modeldata, y)
print("~~~ OLS ~~~")
print('OLS MSE: ', metrics.mean_squared_error(y, lm.predict(modeldata)))
print('OLS R2:', lm.score(modeldata, y))

lm = linear_model.Lasso(alpha=0.1).fit(modeldata, y)
print("~~~ Lasso ~~~")
print('Lasso MSE: ', metrics.mean_squared_error(y, lm.predict(modeldata)))
print('Lasso R2:', lm.score(modeldata, y))

lm = linear_model.Ridge(alpha=0.1).fit(modeldata, y)
print("~~~ Ridge ~~~")
print('Ridge MSE: ', metrics.mean_squared_error(y, lm.predict(modeldata)))
print('Ridge R2:', lm.score(modeldata, y))

~~~ OLS ~~~
('OLS MSE: ', 1672.5811076539349)
('OLS R2:', 0.31193460598906442)
~~~ Lasso ~~~
('Lasso MSE: ', 1673.3956538909761)
('Lasso R2:', 0.31159951845581113)
~~~ Ridge ~~~
('Ridge MSE: ', 1672.5818520781086)
('Ridge R2:', 0.31193429974830278)


### Figuring out the alphas can be done by "hand"

In [26]:
np.logspace(-10, 10, 21)

array([  1.00000000e-10,   1.00000000e-09,   1.00000000e-08,
         1.00000000e-07,   1.00000000e-06,   1.00000000e-05,
         1.00000000e-04,   1.00000000e-03,   1.00000000e-02,
         1.00000000e-01,   1.00000000e+00,   1.00000000e+01,
         1.00000000e+02,   1.00000000e+03,   1.00000000e+04,
         1.00000000e+05,   1.00000000e+06,   1.00000000e+07,
         1.00000000e+08,   1.00000000e+09,   1.00000000e+10])

In [27]:
alphas = np.logspace(-10, 10, 21)
for a in alphas:
    print('Alpha:', a)
    lm = linear_model.Ridge(alpha=a)
    lm.fit(modeldata, y)
    print(lm.coef_)
    print(metrics.mean_squared_error(y, lm.predict(modeldata)))

('Alpha:', 1e-10)
[ 112.68901765  -84.01121684  -24.68489063  -21.00314493  -21.71893628]
1672.58110765
('Alpha:', 1.0000000000000001e-09)
[ 112.68901765  -84.01121684  -24.68489061  -21.00314491  -21.71893626]
1672.58110765
('Alpha:', 1e-08)
[ 112.68901765  -84.01121684  -24.6848904   -21.00314471  -21.71893606]
1672.58110765
('Alpha:', 9.9999999999999995e-08)
[ 112.68901763  -84.01121682  -24.68488837  -21.00314268  -21.71893403]
1672.58110765
('Alpha:', 9.9999999999999995e-07)
[ 112.68901745  -84.01121667  -24.68486804  -21.00312237  -21.71891373]
1672.58110765
('Alpha:', 1.0000000000000001e-05)
[ 112.68901562  -84.01121509  -24.68466472  -21.00291929  -21.71871079]
1672.58110765
('Alpha:', 0.0001)
[ 112.68899732  -84.01119938  -24.68263174  -21.00088873  -21.71668161]
1672.58110765
('Alpha:', 0.001)
[ 112.68881437  -84.01104228  -24.66232204  -20.98060316  -21.69640993]
1672.58110774
('Alpha:', 0.01)
[ 112.68698753  -84.00947323  -24.46121539  -20.77973778  -21.49568404]
1672.58111

### Or we can use grid search to make this faster

In [41]:
from sklearn import grid_search

alphas = np.logspace(-10, 10, 21)


gs = grid_search.GridSearchCV(cv=5, verbose=1,
    estimator=linear_model.Ridge(),
    param_grid={'alpha': alphas},
    scoring='mean_squared_error')

gs.fit(modeldata, y)


Fitting 5 folds for each of 21 candidates, totalling 105 fits


[Parallel(n_jobs=1)]: Done  49 tasks       | elapsed:    0.7s
[Parallel(n_jobs=1)]: Done 105 out of 105 | elapsed:    1.6s finished


GridSearchCV(cv=5, error_score='raise',
       estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'alpha': array([  1.00000e-10,   1.00000e-09,   1.00000e-08,   1.00000e-07,
         1.00000e-06,   1.00000e-05,   1.00000e-04,   1.00000e-03,
         1.00000e-02,   1.00000e-01,   1.00000e+00,   1.00000e+01,
         1.00000e+02,   1.00000e+03,   1.00000e+04,   1.00000e+05,
         1.00000e+06,   1.00000e+07,   1.00000e+08,   1.00000e+09,
         1.00000e+10])},
       pre_dispatch='2*n_jobs', refit=True, scoring='mean_squared_error',
       verbose=1)

In [ ]:
gs = grid_search.GridSearchCV()

In [ ]:
from sklearn.linear_model import Las

##### Best score 

In [35]:
print(gs.best_score_)

-1814.09369133


##### mean squared error here comes in negative, so let's make it positive.

In [36]:
print(-gs.best_score_)

1814.09369133


##### explains which grid_search setup worked best

In [37]:
print(gs.best_estimator_)

Ridge(alpha=10.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)


##### shows all the grid pairings and their performances.

In [38]:
print(gs.grid_scores_)

[mean: -1817.58711, std: 542.14315, params: {'alpha': 1e-10}, mean: -1817.58711, std: 542.14315, params: {'alpha': 1.0000000000000001e-09}, mean: -1817.58711, std: 542.14315, params: {'alpha': 1e-08}, mean: -1817.58711, std: 542.14315, params: {'alpha': 9.9999999999999995e-08}, mean: -1817.58711, std: 542.14315, params: {'alpha': 9.9999999999999995e-07}, mean: -1817.58711, std: 542.14317, params: {'alpha': 1.0000000000000001e-05}, mean: -1817.58707, std: 542.14331, params: {'alpha': 0.0001}, mean: -1817.58663, std: 542.14477, params: {'alpha': 0.001}, mean: -1817.58230, std: 542.15933, params: {'alpha': 0.01}, mean: -1817.54318, std: 542.30102, params: {'alpha': 0.10000000000000001}, mean: -1817.20111, std: 543.63587, params: {'alpha': 1.0}, mean: -1814.09369, std: 556.35563, params: {'alpha': 10.0}, mean: -1818.51694, std: 653.68607, params: {'alpha': 100.0}, mean: -2125.58777, std: 872.45270, params: {'alpha': 1000.0}, mean: -2458.08836, std: 951.30428, params: {'alpha': 10000.0}, me

## Gradient Descent

In [22]:
num_to_approach, start, steps, optimized = 6.2, 0., [-1, 1], False
while not optimized:
    current_distance = num_to_approach - start
    got_better = False
    next_steps = [start + i for i in steps]
    for n in next_steps:
        distance = np.abs(num_to_approach - n)
        if distance < current_distance:
            got_better = True
            print(distance, 'is better than', current_distance)
            current_distance = distance
            start = n
    if got_better:
        print('found better solution! using', current_distance)
        start += 1
    else:
        optimized = True
        print(start, 'is closest to', num_to_approach)


5.2 is better than 6.2
found better solution! using 5.2
3.2 is better than 4.2
found better solution! using 3.2
1.2 is better than 2.2
found better solution! using 1.2
6.0 is closest to 6.2


###Bonus: 
implement a stopping point, similar to what n_iter would do in gradient descent when we've reached "good enough"

##Demo: Application of Gradient Descent 

In [42]:
lm = linear_model.SGDRegressor()
lm.fit(modeldata, y)
print("Gradient Descent R2:", lm.score(modeldata, y))
print("Gradient Descent MSE:", metrics.mean_squared_error(y, lm.predict(modeldata)))

('Gradient Descent R2:', 0.307698505595003)
('Gradient Descent MSE:', 1682.8784159489076)


###Check: Untuned, how well did gradient descent perform compared to OLS?

Answer: 

#Independent Practice: Bike data revisited

There are tons of ways to approach a regression problem. The regularization techniques appended to ordinary least squares optimizes the size of coefficients to best account for error. Gradient Descent also introduces learning rate (how aggressively do we solve the problem), epsilon (at what point do we say the error margin is acceptable), and iterations (when should we stop no matter what?)

For this deliverable, our goals are to:

- implement the gradient descent approach to our bike-share modeling problem,
- show how gradient descent solves and optimizes the solution,
- demonstrate the grid_search module!

While exploring the Gradient Descent regressor object, you'll build a grid search using the stochastic gradient descent estimator for the bike-share data set. Continue with either the model you evaluated last class or the simpler one from today. In particular, be sure to implement the "param_grid" in the grid search to get answers for the following questions:

- With a set of alpha values between 10^-10 and 10^-1, how does the mean squared error change?
- Based on the data, we know when to properly use l1 vs l2 regularization. By using a grid search with l1_ratios between 0 and 1 (increasing every 0.05), does that statement hold true? If not, did gradient descent have enough iterations?
- How do these results change when you alter the learning rate (eta0)?

**Bonus**: Can you see the advantages and disadvantages of using gradient descent after finishing this exercise?

### Starter Code

In [43]:
params = {} # put your gradient descent parameters here
gs = grid_search.GridSearchCV(
    estimator=linear_model.SGDRegressor(),
    cv=cross_validation.KFold(len(modeldata), n_folds=5, shuffle=True),
    param_grid=params,
    scoring='neg_mean_squared_error',
    )

gs.fit(modeldata, y)

print('BEST ESTIMATOR')
print(-gs.best_score_)
print(gs.best_estimator_)
print('ALL ESTIMATORS')
print(gs.grid_scores_)

ValueError: 'neg_mean_squared_error' is not a valid scoring value. Valid options are ['accuracy', 'adjusted_rand_score', 'average_precision', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'log_loss', 'mean_absolute_error', 'mean_squared_error', 'median_absolute_error', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc']

In [20]:
## go for it!